const Data = {
	home: {
		banner: {
			heading: "Unlock your greatest potential with us",
			para: "Join Emissary to connect with the fastest-growing community of diverse leaders worldwide and access top opportunities from the world's greatest companies.",
			btn_01: "Learn More",
			btn_link_01: "/about",
			btn_02: "Join us today",
			btn_link_02: "/signup",
			video: "/videos/Office - 69952.mp4",
		},
		brands: {
			icons: [
				{
					id: 1,
					src: "/images/brands/1.png",
					alt: "Brand_01",
				},
				{
					id: 2,
					src: "/images/brands/2.png",
					alt: "Brand_02",
				},
				{
					id: 3,
					src: "/images/brands/3.png",
					alt: "Brand_03",
				},
				{
					id: 4,
					src: "/images/brands/4.png",
					alt: "Brand_04",
				},
				{
					id: 5,
					src: "/images/brands/5.png",
					alt: "Brand_05",
				},
				{
					id: 6,
					src: "/images/brands/6.png",
					alt: "Brand_06",
				},
				{
					id: 7,
					src: "/images/brands/7.png",
					alt: "Brand_07",
				},
			],
		},
		blocks: {
			sec_bg: "/images/layer_01.svg",
			heading: "Emissary Recruiting Solutions",
			para: "We’re a digital marketing agency on a mission to move digital forwards - and that means doing things a certain way. We measure our success not just by how quickly we reach our destination, but how we get there and what happens along the way. We take time to explore, consult, recalibrate: only then do we move forward. Here’s what else we’re about.",
			btn: "Learn More",
			btn_link: "/about",
			block: [
				{
					id: 1,
					title: "No egos.",
					para: "We believe in the power of collaboration. From the Founder to the office junior, we’re all in this together - and the same goes for our clients.",
				},
				{
					id: 2,
					title: "Never stop learning.",
					para: "We never sit still. We stay ahead of the curve by seeking better ways to do things, then sharing that knowledge with our clients.",
				},
				{
					id: 3,
					title: "Act with integrity.",
					para: "We tell it like it is. We’re honest, transparent and, above all, accountable. We wear our integrity like a badge of honour.",
				},
			],
		},
		serve: {
			heading: "Your recruiting success is our business",
			para: "Here are some opportunities with the best companies in the market today. Join our network and we can work together to find you what fits you.",
			block: [
				{
					id: 1,
					src: "/images/group-young-business-377106.jpg",
					title: "For companies",
					subtitle: "Leave The Work to Us!",
					para: "We have a team of diverse professionals standing by to support your organization’s financial, accounting, recruitment, or other HR needs. We are here to handle the administrative functions that allow you and your team more time to focus on your business strategy and growth.",
					btn: "Join our Network",
					btn_link: "/services/service-detail",
				},
				{
					id: 2,
					src: "/images/Depositphotos_201318592_original.jpg",
					title: "For jobseekers",
					subtitle: "Let’s Get You to Work!",
					para: "Become a part of our talent network and talk to our experienced team of recruiters so that they can match you with the perfect role! We specialize in onsite, hybrid, and remote opportunities in organizations worldwide. Our clients range from small businesses to up-and-coming tech superstars!",
					btn: "Join our Network",
					btn_link: "/services/service-detail",
				},
			],
		},
		choose: {
			sec_bg: "/images/layer_02.svg",
			heading: "Full Service Digital Marketing Agency and Consultancy",
			para: "Full Service Digital Marketing Agency and Consultancy can help you get a handle on your digital marketing from local seo solutions to client conversion software.",
			block: [
				{
					id: 1,
					icon: "/images/icon-roller.svg",
					title: "Online Reputation Management",
					para: "Analyzing negative materials about your brand and addressing them with sentiment analysis and press release distribution.",
				},
				{
					id: 2,
					icon: "/images/icon-stats-up.svg",
					title: "Conversion Rate Optimization",
					para: "We can help fine tune your entire lead acquisition to sales conversion process. From top of tunnel to bottom and through the close.",
				},
				{
					id: 3,
					icon: "/images/icon-blackboard.svg",
					title: "Real-Time Social Media Analytics",
					para: "We produce bespoke reports and technical audits that can help your business with specific areas of digital marketing.",
				},
			],
		},
		pricing: {
			heading: "Our Pricing Plans",
			block: [
				{
					id: 1,
					title: "Business",
					price: "$99",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
				{
					id: 2,
					title: "Professional",
					price: "$219",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
				{
					id: 3,
					title: "Enterprise",
					price: "$419",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
			],
		},
		agency: {
			sec_bg: "/images/layer_03.svg",
			heading: "Match the Best Talent",
			subheading: "Your Ideal Client Is Looking For You",
			para_01: "We are able to match the best talent in the market for your business requirement.",
			para_02: "Our Talent Acquisition Managers are continuously connecting, building talent networks, and outlining individual talent information; that will be able to provide you with the necessary insight into the skills, background, motivations, and expectations of talent in order to properly assess and profile them.",
			para_03: "Our Marketing and Business Development Managers also take the time to understand your organization, and are able to get a clear overview of the enterprise, the organizational structure, the company values, goals, and culture.",
			para_04: "It is through this process that we are able to quickly endorse talent that have the required skills, background, and experience; for your company.",
			src: "/images/IA360-Sponsored-Article-Featured-Image.jpg",
		},
		posts: {
			heading: "See ",
			heading_ex: "Our Blogs",
			block: [
				{
					id: 1,
					title: "9 of the best professional biological examples we have ever seen",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "28 February, 2022",
					src: "/images/Depositphotos_201318592_original.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 2,
					title: "Blog SEO: How to optimize the search engines for your blog content",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "07 July, 2021",
					src: "/images/Businesswoman hand working light.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 3,
					title: "Email forwarding tips you must know by 2020",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "19 May 2020",
					src: "/images/digital-transformation-teaser.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
			],
		},
	},
	about: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Get to know us",
		},
		intro: {
			sec_bg: "/images/layer_01.svg",
			heading: "What are ",
			heading_ex: "we doing",
			subtitle: "Hosting opens up a world of opportunity",
			para: "Odit sint debitis soluta perferendis totam aperiam hic eum numquam dolore laboriosam eius id odio commodi, expedita accusamus amet obcaecati ipsum dicta, fuga maxime reiciendis.",
			ul: [
				{
					id: 1,
					li: "Full-service electrical layout, design",
				},
				{
					id: 2,
					li: "Wiring and installation/upgrades",
				},
				{
					id: 3,
					li: "Emergency power solutions (generators)",
				},
				{
					id: 4,
					li: "Virtually any electrical needs you have – just ask!",
				},
			],
			btn: "Contact us",
			btn_link: "/contact",
			src: "/images/group-young-business-377106.jpg",
		},
		assets: {
			sec_bg: "/images/Depositphotos_201318592_original.jpg",
			heading: "Our mission is to connect the best talent with the best startups in the world.",
			para: "A video is worth 1.8 million words.",
			btn_img_src: "/images/play_icon.svg",
		},
		team: {
			heading: "Team ",
			heading_ex: "Member",
			block: [
				{
					id: 1,
					title: "August Dueholm",
					subtitle: "Presidents",
					src: "/images/01.jpg",
				},
				{
					id: 2,
					title: "Carl Vinter",
					subtitle: "Co-President",
					src: "/images/02.jpg",
				},
				{
					id: 3,
					title: "Sofus Koba",
					subtitle: "Head of Partner Relations",
					src: "/images/03.jpg",
				},
				{
					id: 4,
					title: "Simone Holm",
					subtitle: "Partner Relations Team",
					src: "/images/04.jpg",
				},
			],
		},
	},
	blog: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Blog Posts",
		},
		posts: {
			block: [
				{
					id: 1,
					title: "9 of the best professional biological examples we have ever seen",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "28 February, 2022",
					src: "/images/Businesswoman hand working light.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 2,
					title: "Blog SEO: How to optimize the search engines for your blog content",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "07 July, 2021",
					src: "/images/email_marketing.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 3,
					title: "Email forwarding tips you must know by 2020",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "19 May 2020",
					src: "/images/graphic_design.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 4,
					title: "The best newsletter templates and resources for download right now",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "17 January 2020",
					src: "/images/social_media_marketing.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 5,
					title: "Google Doc features you didn't know existed (but absolutely needed)",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "30 October 2020",
					src: "/images/Depositphotos_201318592_original.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 6,
					title: "Spoken and repeated jokes to satisfy your inner grammar",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "19 May 2020",
					src: "/images/ppc.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 7,
					title: "The Instagram profile anatomy is perfect",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "17 January 2020",
					src: "/images/group-young-business-377106.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 8,
					title: "25 Tips and Tricks for Marketing on Facebook",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "30 October 2020",
					src: "/images/web_design.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 9,
					title: "How to create infographic in less than an hour ",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "19 May 2020",
					src: "/images/seo.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
				{
					id: 10,
					title: "The best time to post on Instagram, Facebook, Twitter and Pinterest",
					para: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Officia delectus illum dolorum consectetur Officia delectus illum dolorum consectetur.",
					date: "07 July, 2021",
					src: "/images/digital-transformation-teaser.jpg",
					btn: "Learn More",
					btn_link: "/blog/blog-detail",
				},
			],
			category: {
				title: "Categories",
				ul: [
					{
						id: 1,
						li: "Science",
						link: "/blog/blog-detail",
					},
					{
						id: 2,
						li: "Information Technology",
						link: "/blog/blog-detail",
					},
					{
						id: 3,
						li: "Artificial Intelligence",
						link: "/blog/blog-detail",
					},
					{
						id: 4,
						li: "Craftsmanship",
						link: "/blog/blog-detail",
					},
					{
						id: 5,
						li: "Professional Beauty",
						link: "/blog/blog-detail",
					},
					{
						id: 6,
						li: "Agriculture",
						link: "/blog/blog-detail",
					},
				],
			},
		},
	},
	blog_detail: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Blog Detail",
		},
		posts: {
			details: {
				title: "9 of the best professional biological examples we have ever seen",
				date: "28 February, 2022",
				src: "/images/Businesswoman hand working light.jpg",
			},
			category: {
				title: "Categories",
				ul: [
					{
						id: 1,
						li: "Science",
						link: "/blog/blog-detail",
					},
					{
						id: 2,
						li: "Information Technology",
						link: "/blog/blog-detail",
					},
					{
						id: 3,
						li: "Artificial Intelligence",
						link: "/blog/blog-detail",
					},
					{
						id: 4,
						li: "Craftsmanship",
						link: "/blog/blog-detail",
					},
					{
						id: 5,
						li: "Professional Beauty",
						link: "/blog/blog-detail",
					},
					{
						id: 6,
						li: "Agriculture",
						link: "/blog/blog-detail",
					},
				],
			},
		},
	},
	contact: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Contact us",
		},
		contact: {
			heading: "Get in Touch",
			para: "Feel free to ask questions on the phone or contact us through our contact form. Your message will be sent directly to our team to get back to you shortly.",
			subheading: "Questions or comments",
			info_blk: [
				{
					id: 1,
					icon: "/images/icon-map-marker.svg",
					title: "Visit the office",
					text: "22, Hoxton, Wenlock Road, London, N1 7TA",
					// link: "javascript:void(0)",
				},
				{
					id: 2,
					icon: "/images/icon-phone.svg",
					title: "Phone Number",
					text: "+1 479.322.4433",
					link: "tel:+1 479.322.4433",
				},
				{
					id: 3,
					icon: "/images/icon-envelope-fill.svg",
					title: "Email Address",
					text: "info@emissarysearch.com",
					link: "mailto:info@emissarysearch.com",
				},
			],
			form: {
				heading: "Drop us a message",
				btn: "Send Message",
			},
		},
	},
	faq: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "FAQ’s",
		},
		faqs: {
			block: [
				{
					id: 1,
					qst: "Obcaecati laborum architecto neque possimus?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 2,
					qst: "Lorem ipsum dolor sit, amet consectetur adipisicing elit?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 3,
					qst: "Deleniti illum ex numquam eos laudantium?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 4,
					qst: "Molestias quidem, maiores reiciendis sint?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 5,
					qst: "Iusto harum temporibus vel, rem numquam quia?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 6,
					qst: "Molestias quidem, maiores reiciendis sint?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
				{
					id: 7,
					qst: "Iusto harum temporibus vel, rem numquam quia?",
					ans: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
				},
			],
		},
	},
	pricing: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Pricing Plan",
		},
		plan: {
			// heading: "Our Pricing Plans",
			block: [
				{
					id: 1,
					title: "Business",
					price: "$99",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
				{
					id: 2,
					title: "Professional",
					price: "$219",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
				{
					id: 3,
					title: "Enterprise",
					price: "$419",
					duration: "/month",
					list: [
						{
							id: 1,
							li: "5GB Linux Web Space",
						},
						{
							id: 2,
							li: "5 MySQL Databases",
						},
						{
							id: 3,
							li: "Unlimited Email",
						},
						{
							id: 4,
							li: "250Gb Monthly Transfer",
						},
						{
							id: 5,
							li: "24/7 Tech Support",
						},
						{
							id: 6,
							li: "Daily Backups",
						},
					],
					btn: "Get Started",
					btn_link: "/dashboard",
				},
			],
		},
	},
	privacy: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Privacy Policy",
		},
	},
	disclaim: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Disclaimer",
		},
	},
	terms: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Terms & Conditions",
		},
	},
	find_jobs: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Find Jobs",
		},
		job_list: {
			heading: "Search Jobs",
			show_result: "Showing 1-30 of 33,013 search results.",
			jobs: [
				{
					id: 1,
					src: "/images/companies/01.png",
					alt: "Surge",
					title: "Senior Full-Stack Software Engineer - React / Node.js",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "1 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 2,
					src: "/images/companies/02.png",
					alt: "ABA",
					title: "Full-time Content Creator",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "2 Year",
					location: "Islamabad",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 3,
					src: "/images/companies/03.png",
					alt: "Asterik",
					title: "Senior Technical Specialist - Service Now",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "3 Year",
					location: "Karachi",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 4,
					src: "/images/companies/04.png",
					alt: "Cuku",
					title: "Trainee Project Coordinator - Part time",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "4 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 5,
					src: "/images/companies/05.png",
					alt: "OKTA",
					title: "Software Engineer / Senior Software Engineer",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "5 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 6,
					src: "/images/companies/01.png",
					alt: "Surge",
					title: "Senior Full-Stack Software Engineer - React / Node.js",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "6 Year",
					location: "Islamabad",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 7,
					src: "/images/companies/02.png",
					alt: "ABA",
					title: "Full-time Content Creator",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "7 Year",
					location: "Multan",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 8,
					src: "/images/companies/03.png",
					alt: "Asterik",
					title: "Senior Technical Specialist - Service Now",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "8 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 9,
					src: "/images/companies/04.png",
					alt: "Cuku",
					title: "Trainee Project Coordinator - Part time",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "9 Year",
					location: "Multan",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
				{
					id: 10,
					src: "/images/companies/05.png",
					alt: "OKTA",
					title: "Software Engineer / Senior Software Engineer",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "10 Year",
					location: "Karachi",
					salary: "40K - 60K",
					act_btn: {
						view: "View Detail",
					},
				},
			],
		},
	},
	solution: {
		cover: {
			sec_bg: "/images/email_marketing.jpg",
			heading: "Solutions",
		},
		agency: {
			sec_bg: "/images/layer_03.svg",
			heading: "Match the Best Talent",
			subheading: "Your Ideal Client Is Looking For You",
			para_01: "We are able to match the best talent in the market for your business requirement.",
			para_02: "Our Talent Acquisition Managers are continuously connecting, building talent networks, and outlining individual talent information; that will be able to provide you with the necessary insight into the skills, background, motivations, and expectations of talent in order to properly assess and profile them.",
			para_03: "Our Marketing and Business Development Managers also take the time to understand your organization, and are able to get a clear overview of the enterprise, the organizational structure, the company values, goals, and culture.",
			para_04: "It is through this process that we are able to quickly endorse talent that have the required skills, background, and experience; for your company.",
			src: "/images/Depositphotos_201318592_original.jpg",
		},
		serve: {
			heading: "Your recruiting success is our business",
			para: "Here are some opportunities with the best companies in the market today. Join our network and we can work together to find you what fits you.",
			block: [
				{
					id: 1,
					src: "/images/group-young-business-377106.jpg",
					title: "For companies",
					subtitle: "Leave The Work to Us!",
					para: "We have a team of diverse professionals standing by to support your organization’s financial, accounting, recruitment, or other HR needs. We are here to handle the administrative functions that allow you and your team more time to focus on your business strategy and growth.",
					btn: "Join our Network",
					btn_link: "/services/service-detail",
				},
				{
					id: 2,
					src: "/images/Depositphotos_201318592_original.jpg",
					title: "For jobseekers",
					subtitle: "Let’s Get You to Work!",
					para: "Become a part of our talent network and talk to our experienced team of recruiters so that they can match you with the perfect role! We specialize in onsite, hybrid, and remote opportunities in organizations worldwide. Our clients range from small businesses to up-and-coming tech superstars!",
					btn: "Join our Network",
					btn_link: "/services/service-detail",
				},
			],
		},
	},
	signin: {
		heading: "Sign in",
		para: "Don’t have an account?",
		para_ex: "Sign up",
		para_link: "/signup",
		form: {
			btn: "Sign in",
		},
		forgot: "Forgot Password?",
		forgot_link: "/forgot-password",
	},
	signup: {
		heading: "Sign up",
		para: "Already have an account?",
		para_ex: "Sign in",
		para_link: "/signin",
		form: {
			btn: "Create Account",
			label: {
				text_01: "Privacy Policy",
				link_01: "/privacy-policy",
				text_02: "Terms & Conditions",
				link_02: "/terms-conditions",
			},
		},
	},
	forgot: {
		heading: "Forgot Password",
		para: "Don’t worry. Just enter the email address you registered with and we’ll email you instructions to reset your password.",
		form: {
			btn: "Reset Password",
		},
	},
	reset: {
		heading: "Reset Password",
		para: "Enter a new password for your account.",
		form: {
			btn: "Change Password",
		},
	},
	dashboard: {
		account: {
			heading_01: "Stastics",
			card: [
				{
					id: 1,
					num: "450",
					text: "Total Jobs",
				},
				{
					id: 2,
					num: "1500",
					text: "Total Candidates",
				},
				{
					id: 3,
					num: "175",
					text: "Total vetted Candidates",
				},
			],
			heading_02: "Open Jobs",
			btn: "Post new job",
			btn_link: "/add-new-job",
			jobs: [
				{
					id: 1,
					src: "/images/companies/01.png",
					alt: "Surge",
					title: "Senior Full-Stack Software Engineer - React / Node.js",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "1 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 2,
					src: "/images/companies/02.png",
					alt: "ABA",
					title: "Full-time Content Creator",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "2 Year",
					location: "Islamabad",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 3,
					src: "/images/companies/03.png",
					alt: "Asterik",
					title: "Senior Technical Specialist - Service Now",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "3 Year",
					location: "Karachi",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 4,
					src: "/images/companies/04.png",
					alt: "Cuku",
					title: "Trainee Project Coordinator - Part time",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "4 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 5,
					src: "/images/companies/05.png",
					alt: "OKTA",
					title: "Software Engineer / Senior Software Engineer",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "5 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 6,
					src: "/images/companies/01.png",
					alt: "Surge",
					title: "Senior Full-Stack Software Engineer - React / Node.js",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "6 Year",
					location: "Islamabad",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 7,
					src: "/images/companies/02.png",
					alt: "ABA",
					title: "Full-time Content Creator",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "7 Year",
					location: "Multan",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 8,
					src: "/images/companies/03.png",
					alt: "Asterik",
					title: "Senior Technical Specialist - Service Now",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "8 Year",
					location: "Lahore",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 9,
					src: "/images/companies/04.png",
					alt: "Cuku",
					title: "Trainee Project Coordinator - Part time",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "9 Year",
					location: "Multan",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
				{
					id: 10,
					src: "/images/companies/05.png",
					alt: "OKTA",
					title: "Software Engineer / Senior Software Engineer",
					para: "Soluta corrupti saepe porro rerum et nihil maiores adipisci quisquam architecto iste deserunt aut, quas ex explicabo corporis iure. Totam, itaque facere!",
					link: "/job-detail",
					company: "Envision Technologies Inc.",
					company_link: "https://www.google.com/",
					date: "Apr 25, 2022",
					experience: "10 Year",
					location: "Karachi",
					salary: "40K - 60K",
					act_btn: {
						view: "Edit",
					},
				},
			],
		},
	},
	settings: {
		personal_info: {
			heading: "Personal information",
			dp: "/images/01.jpg",
			dp_alt: "DP",
		},
		address_info: {
			heading: "Address information",
		},
		change_pass: {
			heading: "Change Password",
		},
	},
	packages: {
		block: [
			{
				id: 1,
				title: "Business",
				price: "$99",
				duration: "/month",
				list: [
					{
						id: 1,
						li: "5GB Linux Web Space",
					},
					{
						id: 2,
						li: "5 MySQL Databases",
					},
					{
						id: 3,
						li: "Unlimited Email",
					},
					{
						id: 4,
						li: "250Gb Monthly Transfer",
					},
					{
						id: 5,
						li: "24/7 Tech Support",
					},
					{
						id: 6,
						li: "Daily Backups",
					},
				],
				btn: "Get Started",
				btn_link: "/dashboard",
			},
			{
				id: 2,
				title: "Professional",
				price: "$219",
				duration: "/month",
				list: [
					{
						id: 1,
						li: "5GB Linux Web Space",
					},
					{
						id: 2,
						li: "5 MySQL Databases",
					},
					{
						id: 3,
						li: "Unlimited Email",
					},
					{
						id: 4,
						li: "250Gb Monthly Transfer",
					},
					{
						id: 5,
						li: "24/7 Tech Support",
					},
					{
						id: 6,
						li: "Daily Backups",
					},
				],
				btn: "Get Started",
				btn_link: "/dashboard",
			},
			{
				id: 3,
				title: "Enterprise",
				price: "$419",
				duration: "/month",
				list: [
					{
						id: 1,
						li: "5GB Linux Web Space",
					},
					{
						id: 2,
						li: "5 MySQL Databases",
					},
					{
						id: 3,
						li: "Unlimited Email",
					},
					{
						id: 4,
						li: "250Gb Monthly Transfer",
					},
					{
						id: 5,
						li: "24/7 Tech Support",
					},
					{
						id: 6,
						li: "Daily Backups",
					},
				],
				btn: "Get Started",
				btn_link: "/dashboard",
			},
		],
	},
	transactions: {
		heading: "Wallet summary",
		table: {
			thead: {
				num: "Order No.",
				name: "Owner Name",
				price: "Amount",
				date: "Date",
				status: "Status",
			},
			tbody: {
				td: [
					{
						id: 1,
						num: "000012",
						name: "John Wick",
						price: "$10.00",
						date: "Fri, 12 Nov 2021",
						status: "Completed",
					},
					{
						id: 2,
						num: "000011",
						name: "Brent Phillips",
						price: "$30.00",
						date: "Tue, 09 Nov 2021",
						status: "Completed",
					},
					{
						id: 3,
						num: "000010",
						name: "Monica Cajrval",
						price: "$60.00",
						date: "Wed, 03 Nov 2021",
						status: "Completed",
					},
					{
						id: 4,
						num: "000009",
						name: "Sasha Smith",
						price: "$10.00",
						date: "Wed, 27 Oct 2021",
						status: "Completed",
					},
					{
						id: 5,
						num: "000008",
						name: "Lara Benz",
						price: "$65.00",
						date: "Thu, 30 Sep 2021",
						status: "Completed",
					},
					{
						id: 6,
						num: "000007",
						name: "Tom Hankle",
						price: "$50.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
					{
						id: 7,
						num: "000006",
						name: "Samira Jones",
						price: "$32.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
					{
						id: 8,
						num: "000005",
						name: "Jennifer Kem",
						price: "$10.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
					{
						id: 9,
						num: "000004",
						name: "Lara Benz",
						price: "$65.00",
						date: "Thu, 30 Sep 2021",
						status: "Completed",
					},
					{
						id: 10,
						num: "000003",
						name: "Tom Hankle",
						price: "$50.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
					{
						id: 11,
						num: "000002",
						name: "Samira Jones",
						price: "$32.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
					{
						id: 12,
						num: "000001",
						name: "Jennifer Kem",
						price: "$10.00",
						date: "Thu, 23 Sep 2021",
						status: "Completed",
					},
				],
			},
		},
	},
	error: {
		sec_bg: "/images/layer_02.svg",
		num: "404",
		title: "Page not found",
		para: "Let's pretend ..... !! You never saw that. Go back to the Homepage to find out more.",
		btn: "Back to the website",
		btn_link: "/",
	},
};

export default Data;
